<?php

namespace AppBundle\Repository;

/**
 * ClidDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClidDataRepository extends \Doctrine\ORM\EntityRepository
{
}
